// GENERATED FILE - DO NOT EDIT.
// Source SHA-256: 9FFB8F5B3DB4DA50ED4537DF4517E53D39191D3E6AA024C2A88AAC42E50E30A6
using System.Collections.ObjectModel;

namespace SRS3.E2E.PanelControl.Models
{
    internal static class RxPanelMetadata
    {
        internal static ObservableCollection<RxGroupRow> CreateGroups()
        {
            return new ObservableCollection<RxGroupRow>
            {
                new RxGroupRow(0, "CAN1", "0x010", "SrsZCUDCAN1Fr02", "CrashStsSafe", 4, 200, 800, 1035, 14, 5, 15, 3, new RxElementDefinition[] { new RxElementDefinition("Sts", "CrashStsSafeSts", 4, 1, false) }),
                new RxGroupRow(1, "CAN1", "0x012", "SrsZCUDCAN1Fr03", "ADataRawSafe", 8, 10, 50, 34, 3, 56, 7, 15, new RxElementDefinition[] { new RxElementDefinition("ALat", "ADataRawSafeALat", 23, 15, true), new RxElementDefinition("ALat1Qf", "ADataRawSafeALat1Qf", 11, 2, false), new RxElementDefinition("ALgt", "ADataRawSafeALgt", 38, 15, true), new RxElementDefinition("ALgt1Qf", "ADataRawSafeALgt1Qf", 9, 2, false), new RxElementDefinition("AVert", "ADataRawSafeAVert", 55, 15, true), new RxElementDefinition("AVertQf", "ADataRawSafeAVertQf", 24, 2, false) }),
                new RxGroupRow(2, "CAN1", "0x013", "SrsZCUDCAN1Fr04", "AsyDataWithCmpSafe", 8, 10, 50, 36, 14, 56, 23, 47, new RxElementDefinition[] { new RxElementDefinition("ALat1Qf", "AsyDataWithCmpSafeALat1Qf", 41, 2, false), new RxElementDefinition("ALatWithCmp", "AsyDataWithCmpSafeALatWithCmp", 55, 15, true), new RxElementDefinition("ALgt1Qf", "AsyDataWithCmpSafeALgt1Qf", 43, 2, false), new RxElementDefinition("GrdtOfALgt", "AsyDataWithCmpSafeGrdtOfALgt", 31, 14, true), new RxElementDefinition("YawRateQf", "AsyDataWithCmpSafeYawRateQf", 33, 2, false), new RxElementDefinition("YawRateWithCmp", "AsyDataWithCmpSafeYawRateWithCmp", 7, 16, true) }),
                new RxGroupRow(3, "CAN1", "0x021", "SrsZCUDCAN1Fr05", "BltLockStSafeAtDrvr", 8, 10, 50, 1036, 14, 14, 23, 11, new RxElementDefinition[] { new RxElementDefinition("BltLockSt1", "BltLockStSafeAtDrvrBltLockSt1", 13, 1, false), new RxElementDefinition("BltLockStErrSts", "BltLockStSafeAtDrvrBltLockStErrSts", 12, 1, false) }),
                new RxGroupRow(4, "CAN1", "0x070", "SrsZCUDCAN1Fr10", "RecOfPostImpctBrkgSuspc", 8, 20, 80, 25, 3, 41, 39, 47, new RxElementDefinition[] { new RxElementDefinition("SuspcPostImpctBrkg", "RecOfPostImpctBrkgSuspcSuspcPostImpctBrkg", 43, 2, false) }),
                new RxGroupRow(5, "CAN1", "0x089", "SrsZCUDCAN1Fr01", "AgDataRawSafe", 8, 10, 50, 35, 3, 5, 47, 55, new RxElementDefinition[] { new RxElementDefinition("RollRate", "AgDataRawSafeRollRate", 15, 16, true), new RxElementDefinition("RollRateQf", "AgDataRawSafeRollRateQf", 51, 2, false), new RxElementDefinition("YawRate", "AgDataRawSafeYawRate", 31, 16, true), new RxElementDefinition("YawRateQf", "AgDataRawSafeYawRateQf", 49, 2, false) }),
                new RxGroupRow(6, "CAN1", "0x142", "SrsZCUDCAN1Fr07", "AgDataRaw2Safe", 8, 30, 120, 1028, 13, 6, 15, 3, new RxElementDefinition[] { new RxElementDefinition("PitchRate", "AgDataRaw2SafePitchRate", 23, 16, true), new RxElementDefinition("PitchRateQf", "AgDataRaw2SafePitchRateQf", 5, 2, false) }),
                new RxGroupRow(7, "CAN1", "0x142", "SrsZCUDCAN1Fr07", "PassAirbLampReq", 8, 30, 120, 1141, 14, 33, 47, 51, new RxElementDefinition[] { new RxElementDefinition("ChgOfPassAirbSts", "PassAirbLampReqChgOfPassAirbSts", 32, 1, false), new RxElementDefinition("PassAirbLampDiReq", "PassAirbLampReqPassAirbLampDiReq", 55, 2, false), new RxElementDefinition("PassAirbLampEnaReq", "PassAirbLampReqPassAirbLampEnaReq", 53, 2, false) }),
                new RxGroupRow(8, "CAN1", "0x148", "SrsZCUDCAN1Fr12", "RecOfPostImpctBrkgCfmd", 8, 30, 120, 74, 3, 30, 63, 29, new RxElementDefinition[] { new RxElementDefinition("CrashFrnt", "RecOfPostImpctBrkgCfmdCrashFrnt", 25, 2, false), new RxElementDefinition("CrashLargeAnimal", "RecOfPostImpctBrkgCfmdCrashLargeAnimal", 39, 2, false), new RxElementDefinition("CrashOffroadA", "RecOfPostImpctBrkgCfmdCrashOffroadA", 37, 2, false), new RxElementDefinition("CrashOffroadD", "RecOfPostImpctBrkgCfmdCrashOffroadD", 35, 2, false), new RxElementDefinition("CrashOffroadRT", "RecOfPostImpctBrkgCfmdCrashOffroadRT", 33, 2, false), new RxElementDefinition("CrashOffroadRTsevere", "RecOfPostImpctBrkgCfmdCrashOffroadRTsevere", 47, 2, false), new RxElementDefinition("CrashOz", "RecOfPostImpctBrkgCfmdCrashOz", 45, 2, false), new RxElementDefinition("CrashPed", "RecOfPostImpctBrkgCfmdCrashPed", 43, 2, false), new RxElementDefinition("CrashRe", "RecOfPostImpctBrkgCfmdCrashRe", 41, 2, false), new RxElementDefinition("CrashRollovr", "RecOfPostImpctBrkgCfmdCrashRollovr", 55, 2, false), new RxElementDefinition("CrashSideLe", "RecOfPostImpctBrkgCfmdCrashSideLe", 53, 2, false), new RxElementDefinition("CrashSideRi", "RecOfPostImpctBrkgCfmdCrashSideRi", 51, 2, false), new RxElementDefinition("PostImpctBrkgCfmd", "RecOfPostImpctBrkgCfmdPostImpctBrkgCfmd", 49, 2, false) }),
                new RxGroupRow(9, "CAN1", "0x274", "SrsZCUDCAN1Fr14", "SRSResdSig1ToZCUDMSafety", 8, 80, 320, 3806, 14, 43, 39, 47, new RxElementDefinition[] { new RxElementDefinition("UInt32", "SRSResdSig1ToZCUDMSafetyUInt32", 7, 32, false) }),
                new RxGroupRow(10, "CANFD3", "0x032", "SrsZCUDCANFD3Fr01", "ADataRawSafe", 64, 5, 50, 34, 3, 7, 39, 47, new RxElementDefinition[] { new RxElementDefinition("ALat", "ADataRawSafeALat", 6, 15, true), new RxElementDefinition("ALat1Qf", "ADataRawSafeALat1Qf", 43, 2, false), new RxElementDefinition("ALgt", "ADataRawSafeALgt", 23, 15, true), new RxElementDefinition("ALgt1Qf", "ADataRawSafeALgt1Qf", 41, 2, false), new RxElementDefinition("AVert", "ADataRawSafeAVert", 55, 15, true), new RxElementDefinition("AVertQf", "ADataRawSafeAVertQf", 71, 2, false) }),
                new RxGroupRow(11, "CANFD3", "0x032", "SrsZCUDCANFD3Fr01", "AgDataRawSafe", 64, 5, 50, 35, 3, 69, 111, 119, new RxElementDefinition[] { new RxElementDefinition("RollRate", "AgDataRawSafeRollRate", 79, 16, true), new RxElementDefinition("RollRateQf", "AgDataRawSafeRollRateQf", 115, 2, false), new RxElementDefinition("YawRate", "AgDataRawSafeYawRate", 95, 16, true), new RxElementDefinition("YawRateQf", "AgDataRawSafeYawRateQf", 113, 2, false) }),
                new RxGroupRow(12, "CANFD3", "0x032", "SrsZCUDCANFD3Fr01", "AsyDataWithCmpSafe", 64, 5, 50, 36, 14, 176, 162, 170, new RxElementDefinition[] { new RxElementDefinition("ALat1Qf", "AsyDataWithCmpSafeALat1Qf", 182, 2, false), new RxElementDefinition("ALatWithCmp", "AsyDataWithCmpSafeALatWithCmp", 143, 15, true), new RxElementDefinition("ALgt1Qf", "AsyDataWithCmpSafeALgt1Qf", 180, 2, false), new RxElementDefinition("GrdtOfALgt", "AsyDataWithCmpSafeGrdtOfALgt", 144, 14, true), new RxElementDefinition("YawRateQf", "AsyDataWithCmpSafeYawRateQf", 178, 2, false), new RxElementDefinition("YawRateWithCmp", "AsyDataWithCmpSafeYawRateWithCmp", 127, 16, true) }),
                new RxGroupRow(13, "CANFD3", "0x032", "SrsZCUDCANFD3Fr01", "IntgtIMUDataRawSafe", 64, 5, 50, 6915, 3, 298, 274, 282, new RxElementDefinition[] { new RxElementDefinition("ALat", "IntgtIMUDataRawSafeALat", 239, 15, true), new RxElementDefinition("ALat1Qf", "IntgtIMUDataRawSafeALat1Qf", 294, 2, false), new RxElementDefinition("ALgt", "IntgtIMUDataRawSafeALgt", 240, 15, true), new RxElementDefinition("ALgt1Qf", "IntgtIMUDataRawSafeALgt1Qf", 292, 2, false), new RxElementDefinition("Avert", "IntgtIMUDataRawSafeAvert", 257, 15, true), new RxElementDefinition("AVertQf", "IntgtIMUDataRawSafeAVertQf", 290, 2, false), new RxElementDefinition("PitchRate", "IntgtIMUDataRawSafePitchRate", 191, 16, true), new RxElementDefinition("PitchRateQf", "IntgtIMUDataRawSafePitchRateQf", 288, 2, false), new RxElementDefinition("RollRate", "IntgtIMUDataRawSafeRollRate", 207, 16, true), new RxElementDefinition("RollRateQf", "IntgtIMUDataRawSafeRollRateQf", 302, 2, false), new RxElementDefinition("YawRate", "IntgtIMUDataRawSafeYawRate", 223, 16, true), new RxElementDefinition("YawRateQf", "IntgtIMUDataRawSafeYawRateQf", 300, 2, false) }),
                new RxGroupRow(14, "CANFD3", "0x03F", "SrsZCUDCANFD3Fr02", "CrashStsSafe", 2, 200, 800, 1035, 14, 10, 7, 15, new RxElementDefinition[] { new RxElementDefinition("Sts", "CrashStsSafeSts", 11, 1, false) }),
            };
        }
    }
}
